import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from "web3uikit"
// import ManualHeader from "../components/ManualHeader"
import LotteryEntrance from '../components/LotteryEntrance'
import Header from "../components/Header"
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title> Smart Contract App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Header />
      <LotteryEntrance />

    </div>
  )
}
